@startuml

title __VALIDATORS's Class Diagram__\n

  namespace com.SWEII {
    namespace Validators {
      class com.UserValidator {
          + supports()
          + validate()
      }
    }
  }
  

  com.UserValidator .up.|> org.springframework.validation.Validator
  com.UserValidator o-- com.IUserServices : userService


right footer

endfooter

@enduml
