@startuml

title __VALIDATORS's Class Diagram__\n

  namespace com.SWEII {
    namespace Validators {
      class com.SWEII.Validators.UserValidator {
          + supports()
          + validate()
      }
    }
  }
  

  com.SWEII.Validators.UserValidator .up.|> org.springframework.validation.Validator
  com.SWEII.Validators.UserValidator o-- com.SWEII.Services.UsersServices.IUserServices : userService


right footer

endfooter

@enduml
