@startuml

title __USERSREPOSITORIES's Class Diagram__\n

  namespace com.SWEII {
    namespace Repositories.UsersRepositories {
      interface com.SWEII.Repositories.UsersRepositories.IAdministratorRepository {
          {abstract} + findAllAdministrators()
      }
    }
  }
  

  namespace com.SWEII {
    namespace Repositories.UsersRepositories {
      interface com.SWEII.Repositories.UsersRepositories.INormalUserRepository {
          {abstract} + findAllNormalUsers()
      }
    }
  }
  

  namespace com.SWEII {
    namespace Repositories.UsersRepositories {
      interface com.SWEII.Repositories.UsersRepositories.IStoreOwnerRepository {
          {abstract} + findAllStoreOwners()
      }
    }
  }
  

  namespace com.SWEII {
    namespace Repositories.UsersRepositories {
      interface com.SWEII.Repositories.UsersRepositories.IUserRepository {
          {abstract} + findByEmail()
          {abstract} + findByUsername()
      }
    }
  }
  



right footer


endfooter

@enduml
