version: "3"
services:
  postgres:
    image: saeedmuhammed/postgres:latest
    network_mode: bridge
    container_name: postgres1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=12345
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
  #  restart: unless-stopped
# APP*****************************************
  springbootapp:
    image : saeedmuhammed/apistore:latest
    network_mode: bridge
    container_name: springbootapp
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080:8080
   # restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: {}